[env.production]
RELEASE_FLAG = "--release"

[tasks.default]
alias = "all"

[tasks.all]
dependencies = ["objcopy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-1]
command = "cargo"
args = ["build", "@@remove-empty(RELEASE_FLAG)"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.objcopy]
command = "cargo"
args = ["objcopy", "@@remove-empty(RELEASE_FLAG)", "--", "-O binary", "--strip-all"]
dependencies = ["build-1"]
install_crate = { crate_name = "cargo-binutils", binary = "rust-objcopy", test_arg = ["--help"] }
