[env.production]
RELEASE_FLAG = "--release"

[tasks.default]
alias = "all"

[tasks.all]
dependencies = ["build"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "@@remove-empty(RELEASE_FLAG)"]

[tasks.hwa]
command = "cargo"
args = ["objcopy", "@@remove-empty(RELEASE_FLAG)", "--example", "hwa", "--", "-O", "binary", "--strip-all", "rust.kex"]
#install_crate = { crate_name = "cargo-binutils", binary = "rust-objcopy", test_arg = ["--help"] }
